name: Build plugin under Maven 4.0.0-alpha-4

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Maven 4.0.0-alpha-4

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: 21
          distribution: zulu
      - name: Load Maven 4.0.0-alpha-4
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=4.0.0-alpha-4 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean verify -Dlicense.skip=true -Dmaven.min-version=4.0.0-alpha-4 --no-transfer-progress
