name: Build plugin under Maven 4.0.0-alpha-4

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Maven 4.0.0-alpha-4

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: 21
          distribution: zulu
      - name: Load Maven 4.0.0-alpha-4
        run: mvn -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=4.0.0-alpha-4 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean verify -Dlicense.skip=true -Dmaven.min-version=4.0.0-alpha-4 --no-transfer-progress
